<a href="https://colab.research.google.com/github/spshreya/CPU-Scheduling-python/blob/master/FCFS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
n=int(input("Enter number of processes:"))

Enter number of processes:5


In [0]:
import numpy as np

In [0]:
print("Enter the arrival time for each process:")
at=np.empty(n)

for i in range(n):
   x=int(input())
   at[i]=x
print(at)

Enter the arrival time for each process:
2
0
5
1
4
[2. 0. 5. 1. 4.]


In [0]:
print("Enter the burst time for each process:")
bt=np.empty(n)

for i in range(n):
   x=int(input())
   bt[i]=x
print(bt)

Enter the burst time for each process:
10
3
5
7
2
[10.  3.  5.  7.  2.]


In [0]:
#sorting AT
for i in range(n):
  for j in range(0, n-i-1):
    if at[j] > at[j+1] :
      at[j], at[j+1] = at[j+1], at[j]
      bt[j], bt[j+1] = bt[j+1], bt[j]
print(at)

[0. 1. 2. 4. 5.]


In [0]:
print(bt)

[ 3.  7. 10.  2.  5.]


In [0]:
#calculating CT
ct= np.empty(n)
#for first process ct = at + bt
ct[1]=at[1]+bt[1]
for i in range(1,n):
  ct[i]=ct[i-1]+bt[i]
print(ct)
  

[ 3. 10. 20. 22. 27.]


In [0]:
#calculating turn around time
tat=np.empty(n)
#tat= ct-at
for i in range(n):
  tat[i]=ct[i]-at[i]
print(tat)

[ 3.  9. 18. 18. 22.]


In [0]:
#avg tat
np.average(tat)

14.0

In [0]:
#calculating waiting time
wt=np.empty(n)
#wt= tat-bt
for i in range(n):
  wt[i]=tat[i]-bt[i]
print(wt)

[ 0.  2.  8. 16. 17.]


In [0]:
#avg wt
np.average(wt)

8.6

In [0]:
#creating gantt chart

data= np.array([at,bt,ct,tat,wt])
print(data)

[[ 0.  1.  2.  4.  5.]
 [ 3.  7. 10.  2.  5.]
 [ 3. 10. 20. 22. 27.]
 [ 3.  9. 18. 18. 22.]
 [ 0.  2.  8. 16. 17.]]


In [0]:
import pandas as pd
df = pd.DataFrame(data)
df

0     1     2     3     4
0  0.0   1.0   2.0   4.0   5.0
1  3.0   7.0  10.0   2.0   5.0
2  3.0  10.0  20.0  22.0  27.0
3  3.0   9.0  18.0  18.0  22.0
4  0.0   2.0   8.0  16.0  17.0

In [0]:
df.index=['AT','BT','CT','TAT','WT']
df

0     1     2     3     4
AT   0.0   1.0   2.0   4.0   5.0
BT   3.0   7.0  10.0   2.0   5.0
CT   3.0  10.0  20.0  22.0  27.0
TAT  3.0   9.0  18.0  18.0  22.0
WT   0.0   2.0   8.0  16.0  17.0