<a href="https://colab.research.google.com/github/spshreya/CPU-Scheduling-python/blob/master/SJF_Preempt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [19]:
n=int(input('Enter the number of processes:'))

Enter the number of processes:5


In [20]:
p = list(np.arange(1,n+1,1))
print(p)

[1, 2, 3, 4, 5]


In [21]:
print("Enter the arrival time for each process:")
at=np.empty(n)
for i in range(n):
  x=int(input())
  at[i]=x
print(at)

Enter the arrival time for each process:
1
4
2
5
3
[1. 4. 2. 5. 3.]


In [31]:
print("Enter the burst time for each process:")
bt=np.empty(n)
btc=np.empty(n)
for i in range(n):
  x=int(input())
  bt[i]=x
print(bt)
btc=bt
print(btc)

Enter the burst time for each process:
10
2
3
6
1
[10.  2.  3.  6.  1.]
[10.  2.  3.  6.  1.]


In [23]:
complete=sum(bt)+at[0]
print(complete)

23.0


In [0]:
#linear search because we need to use FCFS in case of a tie in the min BT
def search(arr, x): 
  
    for temp in range(len(arr)): 
  
        if arr[temp] == x: 
            return temp
  
    return -1

In [0]:
def check(t,bt):
  bti=np.empty(0)
  for i in range(n):
    if t>=at[i]:
      
      #print(at[i],i)
      #check=-1
      if bt[i]>=1:
        bti=np.append(bti,bt[i])

  return bti

In [26]:
t=0 
#check=0
ct=np.empty(n)
while complete!=0:
  x=check(t,bt)
  if x.size!=0:
    btmin=np.amin(x)
    temp= search(bt,btmin)
    btmin=btmin-1
    bt[temp]=btmin
    if bt[temp]==0:
      ct[temp]=t+1
    t=t+1
    complete=complete-1
      
  else:
    #check=-2
    t=t+1
    complete=complete-1
print(ct)

[23.  6.  8. 14.  4.]


In [27]:
#calculating Turn around time ct - at
tat=np.empty(n)
for i in range(n):
  tat[i]=ct[i]-at[i]
print(tat)

[22.  2.  6.  9.  1.]


In [32]:
#calculating waiting time tat-bt
wt = np.empty(n)
for i in range(n):
  wt[i]=tat[i]-btc[i]
  #btc was the copy of bt which contains the original values of bt
  #bt has been changed
print(wt)

[12.  0.  3.  3.  0.]


In [29]:
np.average(tat)

8.0

In [33]:
np.average(wt)

3.6

# **GANTT CHART**

In [35]:
data=np.array([at,btc,ct,tat,wt])
data

array([[ 1.,  4.,  2.,  5.,  3.],
       [10.,  2.,  3.,  6.,  1.],
       [23.,  6.,  8., 14.,  4.],
       [22.,  2.,  6.,  9.,  1.],
       [12.,  0.,  3.,  3.,  0.]])

In [37]:
df=pd.DataFrame(data)
df.index=['AT','BT','CT','TAT','WT']
df

0    1    2     3    4
AT    1.0  4.0  2.0   5.0  3.0
BT   10.0  2.0  3.0   6.0  1.0
CT   23.0  6.0  8.0  14.0  4.0
TAT  22.0  2.0  6.0   9.0  1.0
WT   12.0  0.0  3.0   3.0  0.0